// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("https://www.roboform.com/filling-test-all-fields");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.name("01___title")).click();
    driver.findElement(By.name("01___title")).sendKeys("title is agbduyqgd");
    driver.findElement(By.name("02frstname")).click();
    driver.findElement(By.name("02frstname")).sendKeys("gilchrist");
    driver.findElement(By.name("03middle_i")).click();
    driver.findElement(By.name("03middle_i")).sendKeys("idk");
    driver.findElement(By.name("04lastname")).click();
    driver.findElement(By.name("04lastname")).sendKeys("perera");
    driver.findElement(By.name("04fullname")).click();
    driver.findElement(By.name("04fullname")).sendKeys("gil per");
    driver.findElement(By.name("05_company")).click();
    driver.findElement(By.name("05_company")).sendKeys("bmw");
    driver.findElement(By.name("06position")).click();
    driver.findElement(By.name("06position")).sendKeys("manager");
    driver.findElement(By.name("10address1")).click();
    driver.findElement(By.name("10address1")).sendKeys("mnapusa");
    driver.findElement(By.name("11address2")).click();
    driver.findElement(By.name("11address2")).sendKeys("panaji");
    driver.findElement(By.name("13adr_city")).click();
    driver.findElement(By.name("13adr_city")).sendKeys("iucwqje");
    driver.findElement(By.name("16addr_zip")).click();
    driver.findElement(By.name("16addr_zip")).sendKeys("403145");
    driver.findElement(By.name("42ccexp_mm")).click();
    {
      WebElement dropdown = driver.findElement(By.name("42ccexp_mm"));
      dropdown.findElement(By.xpath("//option[. = '11']")).click();
    }
    driver.findElement(By.name("43ccexp_yy")).click();
    {
      WebElement dropdown = driver.findElement(By.name("43ccexp_yy"));
      dropdown.findElement(By.xpath("//option[. = '2022']")).click();
    }
    driver.findElement(By.name("40cc__type")).click();
    {
      WebElement dropdown = driver.findElement(By.name("40cc__type"));
      dropdown.findElement(By.xpath("//option[. = 'Master Card']")).click();
    }
    driver.findElement(By.name("30_user_id")).click();
    driver.findElement(By.name("30_user_id")).sendKeys("21ue");
    driver.findElement(By.name("31password")).click();
    driver.findElement(By.name("31password")).sendKeys("asrt67");
  }
}
